FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Postboy

Asynchronous delivery service for Email or SMS messages.

## Features

- Configurable retry limits (how many to retry delivery: 0 - N - :infinity) and backoff strategy (exponential, static)
- Configurable concurrency limit
- HTTP connection pool for perfomance
- RabbitMQ and HTTP protocols
- Sheduled delivery windows including timezone
- Webhooks

## Notifications [/notifications]

### Send Notification [POST]

+ Request (application/json)
    + Attributes (Notification)
       
+ Response 201 (application/json)
    + Headers
    
            Location: /notifications/123

    + Attributes (Response_OK)
        + meta
            + code: 201
        + data (Notification)
            + id: 19283874747
            + status: accepted (enum, required)
                - accepted (string) - Message is accepted and sheduled for delivery.
                - delivered (string) - Message is delivered to destination gateway.
                - failed (string) - Message can not be delivered (see `failure_reason`).
            + failure_reason (object, optional)


### Get Status [GET /notifications/{external_id}]

+ Parameters
    + external_id: 123 (string, required)

+ Response 200 (application/json)
    + Attributes (Response_OK)
        + data (Notification)
            + status: delivered (enum, required)
                - accepted
                - delivered
                - failed

# Data Structures
## Responses
### `Response_Collection`
+ meta (Response__Meta, fixed-type)
+ data (array[], fixed-type)
+ paging (Response__Pagination, fixed-type)

### `Response_OK`
+ meta (Response__Meta, fixed-type)
+ data (object, fixed-type)

### `Response_Error`
+ meta (Response__Meta, fixed-type)
    + code: 400 (number)
+ error (Response__Error, fixed-type)

### `Response__Meta`
+ code: 200 (number) - HTTP response code.
+ url: http://example.com/resource (string) - URL to requested resource.
+ type (enum) - Type of data that is located in `data` attribute.
    - object (string) - `data` attribute is a JSON object.
    - list (string) - `data` attribute is a list.
+ code: 200 (number) - HTTP response code.
+ `idempotency_key`: `idemp-ssjssdjoa8308u0us0` (string, optional) - [Idempotency key](http://docs.apimanifest.apiary.io/#introduction/optional-features/idempotent-requests). Send it trough `X-Idempotency-Key` header.
+ `request_id`: `req-adasdoijasdojsda` (string) - [Request ID](http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/request-id). Send it with `X-Request-ID` header.

### `Response__Error`
+ type: type_atom (string) - Atom that represents error type.
+ message: Error description (string) - Human-readable error message. This is for developers, not end-users.

### `Response__Error_DuplicateEntity`
+ type: `object_already_exists` (string) - Atom that represents error type.
+ message: This API already exists (string) - Human-readable error message. This is for developers, not end-users.

### `Response__Error_ValidationFailed`
+ type: validation_failed (string) - type of an error.
+ message: Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors. (string)
+ invalid (array)
    + `entry_type`: `json_data_proprty` (string) - Type of error.
    + entry: $.cvv (string) - JSON Path to an invalid property.
    + rules (array)
        + rule: required (string) - String constant that represents validation rule type. List of all types can be found in [API Manifest](http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors).
        + params (array) - Validation Parameters.

### `Response__Pagination`
+ limit: 20 (number) - A limit on the number of objects to be returned, between 1 and 100. Default: 50.
+ cursors (object)
    + `starting_after`: 56c31536a60ad644060041af (string) - A cursor for use in pagination. An object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.
    + `ending_before`: 56c31536a60ad644060041aa (string) - A cursor for use in pagination. An object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.
+ size: 1000 (number) - Total number of objects in collection.
+ has_more: false (boolean) - Is this collection have more data to load in the same style as last request loaded it.

## Notifications
### Notification
+ external_id: 123 (string, optional) - External ID may be used when saving notification ID for later pooling is not desired.
+ channel: email (enum, required) - Delivery channel.
    - email (string)
    - phone (string)
+ to: `bob@example.com` (string, required) - Recipient's ID in specified channel.
+ from: `MyService@example.com` (string, optional) - Sender ID for channels that support it.
+ One of
    + data (`Email_Data`, required)
    + data (`Phone_Data`, required)
+ shedule (Schedule)
+ webhook: `http://example.com/delivery_status` (string, optional)

## Schedules
### `Schedule`
+ timezone: Europe/Kiev
+ rules (array[Schedule__Item], fixed-type)

### `Schedule__Item``
+ weekdays (array[enum], required)
    - monday (string, optional)
    - tuesday (string, optional)
    - wednesday (string, optional)
    - thursday (string, optional)
    - friday (string, optional)
    - sunday (string, optional)
+ timeframes (array[`Schedule__Item__Timeframe`], required)

### `Schedule__Item__Timeframe`
+ from: `11:00:00` (string, required) - Delivery window begin time.
+ to: `15:00:00` (string, required) - Delivery window end time.

## Emails
### `Email_Data`
+ subject: `Hello Bob` (string, required)
+ html_body: `I have a <b>gift</b> for you` (string, required)
+ text_body: `I have a gift for you` (string, optional)

## Phone
### `Phone_Data`
+ text: `Hey, how about to hand out togather?` (string, required)